// Code generated by go-swagger; DO NOT EDIT.

package connect

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ConnectOKCode is the HTTP code returned for type ConnectOK
const ConnectOKCode int = 200

/*ConnectOK OK

swagger:response connectOK
*/
type ConnectOK struct {
}

// NewConnectOK creates ConnectOK with default headers values
func NewConnectOK() *ConnectOK {

	return &ConnectOK{}
}

// WriteResponse to the client
func (o *ConnectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// ConnectBadRequestCode is the HTTP code returned for type ConnectBadRequest
const ConnectBadRequestCode int = 400

/*ConnectBadRequest Bad Request

swagger:response connectBadRequest
*/
type ConnectBadRequest struct {
}

// NewConnectBadRequest creates ConnectBadRequest with default headers values
func NewConnectBadRequest() *ConnectBadRequest {

	return &ConnectBadRequest{}
}

// WriteResponse to the client
func (o *ConnectBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// ConnectNotFoundCode is the HTTP code returned for type ConnectNotFound
const ConnectNotFoundCode int = 404

/*ConnectNotFound Etcd Connection not established

swagger:response connectNotFound
*/
type ConnectNotFound struct {
}

// NewConnectNotFound creates ConnectNotFound with default headers values
func NewConnectNotFound() *ConnectNotFound {

	return &ConnectNotFound{}
}

// WriteResponse to the client
func (o *ConnectNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// ConnectInternalServerErrorCode is the HTTP code returned for type ConnectInternalServerError
const ConnectInternalServerErrorCode int = 500

/*ConnectInternalServerError Internal Server Error

swagger:response connectInternalServerError
*/
type ConnectInternalServerError struct {
}

// NewConnectInternalServerError creates ConnectInternalServerError with default headers values
func NewConnectInternalServerError() *ConnectInternalServerError {

	return &ConnectInternalServerError{}
}

// WriteResponse to the client
func (o *ConnectInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
